openapi: 3.0.0
info:
  title: "Application API Docs"
  version: "1.0.0"
servers:
  - url: "http://localhost:8003/api"
components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: Authorization
paths:
  /user/auth/register:
    post:
      summary: User registration
      description: Register a new user.
      requestBody:
        required: true
        content:
          application/json:
            example:
              email: "roman@gmail.com"
              password: "roman123"
              c_password: "roman123"
              gender: "MALE"
              number: 9843124323
              f_name: "Roman"
              l_name: "Ojha"
      responses:
        "201":
          description: User Registered Successfully
          content:
            application/json:
              example:
                message: "<message>"
                data:
                  id: 1
                  username: "<username>"
                  email: "<email>"
                  f_name: "<f_name>"
                  l_name: "<l_name>"
                  gender: "<gender>"
        "422":
          description: Validation Error
          content:
            application/json:
              example:
                message: "<message>"
                errors:
                  email: ["<error_message>"]
                  password: ["<error_message>"]
                  c_password: ["<error_message>"]
                  gender: ["<error_message>"]
                  number: ["<error_message>"]
                  f_name: ["<error_message"]
                  l_name: ["<error_message>"]
        "500":
          description: Internal Server Error
          content:
            application/json:
              example:
                message: "<message>"

  /user/auth/login:
    post:
      summary: User Login
      description: Log in a user.
      requestBody:
        required: true
        content:
          application/json:
            example:
              email: "roman@gmail.com"
              password: "roman123"
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              example:
                message: "<message>"
                data:
                  token: "<token>"
                  expires_in: "<Date>"
        "500":
          description: Internal Server Error
          content:
            application/json:
              example:
                message: "<message>"
        "401":
          description: Unauthorized
          content:
            application/json:
              example:
                message: "<message>"

  /user/auth/check:
    get:
      summary: Get posts
      description: Retrieve a list of posts.
      security:
        - apiKey: []
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              example:
                - id: 1
                  title: "First Post"
                  content: "This is the content of the first post."
                - id: 2
                  title: "Second Post"
                  content: "This is the content of the second post."
  # Admin Service
  /admin:
    get:
      summary: Get Admins Details
      description: Retrieve a list of Admins
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              example:
                id: 1
                email: "<email>"
                first_name: "<first_name>"
                last_name: "<last_name>"
                number: "<number>"

  /admin/auth/register:
    post:
      summary: Register new admin
      description: ""
      requestBody:
        required: true
        content:
          application/json:
            example:
              email: "razz@gmail.com"
              password: "razzroman@123"
              c_password: "razzroman@123"
              first_name: "Roman"
              last_name: "Ojha"
              number: +9779843212343
      responses:
        "201":
          description: Successful Registered
          content:
            application/json:
              example:
                id: 1
                email: "razz@gmail.com"
                first_name: "Roman"
                last_name: "Ojha"
                number: +9779843212343
        "400":
          description: Validation Error
          content:
            application/json:
              example:
                email: ["<error_message>"]
                password: ["<error_message>"]
                c_password: ["<error_message>"]
                first_name: ["<error_message>"]
                last_name: ["<error_message>"]
                number: ["<error_message"]

  /admin/auth/login:
    post:
      requestBody:
        required: True
        content:
          application/json:
            example:
              email: "razz@gmail.com"
              password: "razzroman@123"

      responses:
        "200":
          description: Successfully Logged in
          content:
            application/json:
              example:
                refresh: "<token>"
                access: "<token>"
        "401":
          description: Unauthorized
          content:
            application/json:
              example:
                detail: "<message>"

  /admin/auth/check:
    get:
      summary: Get user
      description: Retrieve a user detail
      security:
        - apiKey: []
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              example:
                id: 1
                email: "<email>"
                first_name: "<first_name>"
                last_name: "<last_name>"
                number: "<number>"
        "401":
          description: Unauthorized
          content:
            application/json:
              example:
                detail: "Authentication credentials were not provided."
